---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lucilbco/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp *.css $DEPLOYPATH
    - /bin/cp *.js $DEPLOYPATH
    - /bin/cp *.json $DEPLOYPATH
    - /bin/cp *.txt $DEPLOYPATH
    - /bin/cp *.xml $DEPLOYPATH
    - /bin/cp *.ico $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH